#!/bin/sh

PROTECTED_BRANCH='master'
BRANCH=`git rev-parse --abbrev-ref HEAD`
PUSH_COMMAND=`ps -ocommand= -p $PPID`

if [ $BRANCH == $PROTECTED_BRANCH ]; then
  echo ""
  echo "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
  echo "X                WARNING                X"
  echo "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
  echo ""
  echo "Pushing to $PROTECTED_BRANCH is a dangerous operation and is not advisable."
  echo "If you really want to do this, please use --no-verify to bypass this check."
  echo ""
  echo ""
  exit 1
fi

exit 0

